### ISSUE TITLE
Some `data-v-xxxxxxxx` attributes are missing from the app when running `yarn serve`

### ISSUE THREAD

**Issue by lalibi** [cmseguin/rollup-plugin-react-scoped-css#16]
During development, everything seems fine, but when I test the final "product", styles are not applied.

It seems that some `data-v-xxxxxxxx` attributes are missing, even when testing the demo you have here.

Mind you that not all attributes are missing. From my own tests, `data-v-xxxxxxxx` attributes were missing when rendering this:

```jsx
<h1>Hello, {name}!</h1>
```

but not when rendering this:

```jsx
<h1>Hello!</h1>
```

I tried poking around the code, I expected to find an offending `Regex` that couldn't handle `{ }` properly but I couldn't figure it out.

The following two images show the issue in the `simple-vite` example.

## `yarn dev`

![2021-11-20_12-29_chrome_ragso](https://user-images.githubusercontent.com/537748/142723080-ce89d3df-ad03-49f0-9d8e-84bf7f12c40c.png)

## `yarn serve`

![2021-11-20_12-29_chrome_j7GGd](https://user-images.githubusercontent.com/537748/142723083-cf6e10ae-740d-4629-959b-6919262448f4.png)

**Comment by cmseguin** [comment]
Hey! Thanks for reaching out! I have not tested every scenario, so good catch! 
Essentially this is how it works: 
1. babel generates the javascript from the jsx (this used to generate code like React.createElement, but in react 17 transformation is fairly different)
2. my plugin converts the generated code to AST
3. I parse the AST and adds the attributes (this is where the problem seems to be)
4. converts back to js.

I will investigate a bit more and try to come up with a fix today or tomorrow!

I think it would be worth having tests that compiles JSX/TSX to both react < 16 & react >= 17 and right assert statements for these edge cases.

**Comment by cmseguin** [comment]
@lalibi Can you confirm that this PR fixes your issue? I will try to make some tests for this.

**Comment by lalibi** [comment]
> @lalibi Can you confirm that this PR fixes your issue? I will try to make some tests for this.

Yes, it does! I tested both with the `simple-vite` example and my own project.

Thanks for your quick reply.

**Comment by cmseguin** [comment]
Thank you for helping me! :) Don't hesitate to report any other issues!
